//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDadotAngularAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class council
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public council()
        {
            this.employee_in_council = new HashSet<employee_in_council>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> status_id { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string postal_code { get; set; }
        public string email { get; set; }
    
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_in_council> employee_in_council { get; set; }
    }
}
