//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDadotAngularAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_in_council
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_in_council()
        {
            this.rav = new HashSet<rav>();
        }
    
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> code_council { get; set; }
        public Nullable<int> code_role { get; set; }
    
        public virtual council council { get; set; }
        public virtual employee employee { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rav> rav { get; set; }
    }
}
