//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDadotAngularAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datotEntities : DbContext
    {
        public datotEntities()
            : base("name=datotEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agaf> agaf { get; set; }
        public virtual DbSet<council> council { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_in_council> employee_in_council { get; set; }
        public virtual DbSet<location_type> location_type { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<rav> rav { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
