//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDadotAngularAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rav
    {
        public int id { get; set; }
        public Nullable<int> code_employee_in_council { get; set; }
        public Nullable<int> location_id { get; set; }
    
        public virtual employee_in_council employee_in_council { get; set; }
        public virtual locations locations { get; set; }
    }
}
